// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM5cf6DyR3FgQ5Qo-3Z9om6CVAI5gLv3o',
    appId: '1:674823742475:web:23ae3b50953492da99530e',
    messagingSenderId: '674823742475',
    projectId: 'flutter-firebase-1aba7',
    authDomain: 'flutter-firebase-1aba7.firebaseapp.com',
    storageBucket: 'flutter-firebase-1aba7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvu8It0pjcsMqsMZBPPu2A_wHB2eL1iDA',
    appId: '1:674823742475:android:26bf32779685a51899530e',
    messagingSenderId: '674823742475',
    projectId: 'flutter-firebase-1aba7',
    storageBucket: 'flutter-firebase-1aba7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0tnEkE-kYJ5qvk0iaiuyeZGEvu03xzI4',
    appId: '1:674823742475:ios:dbf6a80524763f3f99530e',
    messagingSenderId: '674823742475',
    projectId: 'flutter-firebase-1aba7',
    storageBucket: 'flutter-firebase-1aba7.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0tnEkE-kYJ5qvk0iaiuyeZGEvu03xzI4',
    appId: '1:674823742475:ios:dbf6a80524763f3f99530e',
    messagingSenderId: '674823742475',
    projectId: 'flutter-firebase-1aba7',
    storageBucket: 'flutter-firebase-1aba7.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM5cf6DyR3FgQ5Qo-3Z9om6CVAI5gLv3o',
    appId: '1:674823742475:web:8b6d21f02474c35099530e',
    messagingSenderId: '674823742475',
    projectId: 'flutter-firebase-1aba7',
    authDomain: 'flutter-firebase-1aba7.firebaseapp.com',
    storageBucket: 'flutter-firebase-1aba7.appspot.com',
  );
}
